### ISSUE TITLE
Add revision-sidebar on the main(summary) view

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/firefox-code-coverage-frontend#1]
CC: @yuenj @klahnakoski @armenzg

The revision numbers will be showed in a sidebar on the main view.
The revision number will be clickable.
User should be able to interact with the sidebar to choose which revision she/he wants to browse on

**Comment by marco-c** [comment]
What is the purpose of this?

**Comment by marco-c** [comment]
@marco-c This is to show the tests that cover a file of a particular revision.

**Comment by marco-c** [comment]
@klahnakoski we probably have to redesign the UI, I think a sidebar can be very confusing.
This information should go in a totally separate view.

**Comment by klahnakoski** [comment]
Yes, after reviewing the PR, I did not notice that "main(summary)" view is ambiguous.  For this case the "summary view" refers to viewing a directory and it's coverage stats.  (I would ad an example for codecov.io, but it seems to be down)

**Comment by klahnakoski** [comment]
This is no longer relevant.
