### ISSUE TITLE
Show coverage percentage of test

### ISSUE THREAD

**Issue by yuenj** [klahnakoski/firefox-code-coverage-frontend#11]

**Comment by yuenj** [comment]
Depends on #9

**Comment by klahnakoski** [comment]
I believe the design plan is to show a right-side column containing all the tests that contributed to covering the file.  When clicking on a line, only the tests that cover that line are shown on the left.

**Comment by yuenj** [comment]
I plan to work on showing the coverage percentage of a particular test

**Comment by yuenj** [comment]
We may plan to use this simpler query for showing percentage coverage and total covered for a given test of a file.

> https://activedata.allizom.org/tools/query.html#query_id=5lQshXUY

**Comment by yuenj** [comment]
done!
