### ISSUE TITLE
Style FileViewContainer div

### ISSUE THREAD

**Issue by yuenj** [klahnakoski/firefox-code-coverage-frontend#13]
I was thinking that we can have a box around the source code and top bar similar to how code looks like on github.

**Comment by klahnakoski** [comment]
Nice! Keep it consistent with the diff viewer.  Which may mean opening an issue there, and making a pull request to armenzg's repo to ensure he likes the style.

**Comment by klahnakoski** [comment]
Done some time ?last week?
