### ISSUE TITLE
Color-code the source code

### ISSUE THREAD

**Issue by yuenj** [klahnakoski/firefox-code-coverage-frontend#14]
e.g. comments are a certain color, #include statements are another color, etc.

**Comment by klahnakoski** [comment]
Ensure the styling stays consistent with the diff viewer; at this time there is no styling.

**Comment by klahnakoski** [comment]
You may want to get styling information from hg: 
https://hg.mozilla.org/mozilla-central/file/64bab5cbb9b6/dom/events/Event.cpp
