### ISSUE TITLE
Display tests that cover file

### ISSUE THREAD

**Issue by yuenj** [klahnakoski/firefox-code-coverage-frontend#19]
We need to create a view that shows the tests that cover a given file.

**Comment by LinkaiQi** [comment]
Do you want to do this in a separate page?

**Comment by yuenj** [comment]
Sure, do you want to work on this?  I left a comment on what I'll do in the next little while in the etherpad so we don't conflict.

**Comment by LinkaiQi** [comment]
I can do this if it does not conflict with your work. But I don't know how the view is going to look like. I think I will probably work on #20

**Comment by klahnakoski** [comment]
The display of tests should be the same page as the fileviewer.  @yuenj  had drawn an example view:

https://github.com/armenzg/firefox-code-coverage-frontend/commit/8e416e7f70d62035

Now, the left hand side should be showing a file, not a diff, but I hope you get the idea: The main view is the source code, and the right hand side is a list of tests that match the currently selected line.

When no line is selected, then the RHS list shows all tests that contributed to the coverage of the file

**Comment by klahnakoski** [comment]
This has been done for a while
