### ISSUE TITLE
Add file viewer 

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/firefox-code-coverage-frontend#2]
CC: @LinkaiQi @klahnakoski @armenzg

This viewer would show the coverage, from multiple tests, for a given file, at a given revision.

The user should be able to interact with the UI to know what test covered what lines.

Based on discussions with Kyle,

    We intend to get the sources from hg. Here is an example:
    https://hg.mozilla.org/integration/mozilla-inbound/raw-file/6b0491f83229/accessible/atk/Platform.cpp

    We can get a list of the latest coverage artifacts from ActiveData (coverage sticks around for 3 weeks, so we will use this to get new revision numbers when the old ones expire):
    https://activedata.allizom.org/tools/query.html#query_id=70sYgySl

    We can look at the coverage for a particular source file; each record is from a chunk of a test suite (aka "a test"): https://activedata.allizom.org/tools/query.html#query_id=WdGo1H+i

There is a drawing of this idea in the docs directory.

**Comment by marco-c** [comment]
From https://github.com/armenzg/firefox-code-coverage-frontend/issues/51, @klahnakoski said:
> @marco-c once the students have a working prototype they will be in a position to declare the type of data they require from the backend.

**Comment by marco-c** [comment]
I guess the only information needed will be the coverage information (array of coverage counts for each line) for a given file at a given revision.

**Comment by klahnakoski** [comment]
This fork is solving this issue.  We will open an issue in armenzg's repo, when we are ready.
