### ISSUE TITLE
Refactor getRawFile and getFileRevisionCoverage

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/firefox-code-coverage-frontend#22]
`getRawFile` and `getFileRevisionCoverage` have common code: Make a new function that contains that code.  This should reduce both those functions to a single line.

**Comment by klahnakoski** [comment]
Here is an example of what I am looking for.

First, remove the callbacks from the functions; you can use promises instead:

    /* Fetch source code from hg */
    FetchAPI.getRawFile(this.revision, this.path)
      .then(text => this.setState({ parsedFile: text.split("\n") }))
    ;

    /* Fetch coverages from ActiveData */
    FetchAPI.getFileRevisionCoverage(this.revision, this.path)
    .then(data => {
      this.setState({coverage: data});
      // TODO remove these log lines
      console.log(data);
    });

Next, make a function that will act as a facade for the `fetch` call:

    export const httpFetch = (params) =>
      fetch(
        params.url,
        {
          ...plainHeaders,
          ...params.headers,
          ...{method: "GET"},
          method: params.method,
          body: params.body
        }
      )
      .then(response => {
        if (response.status !== 200) {
          throw Error('Error status code' + response.status);
        }
        return response.text();
      })
      .catch(error => {
        throw Error('Problem fetching from URL' + error);
      })
    ;

This does three things

1, catches errors, and throws new ones. It would be nice to have a library that can perform exception chaining instead of `+ error` that I did.
2. deals with non 200 responses
3. takes named parameters,with defaults, and maps them to `fetch` parameters

Also notice this function is a promise, so we can avoid the callback.

Here a function that uses `httpFetch`:

    export const jsonPost = (params) =>
      httpFetch({
        url: params.url,
        method: "POST",
        body: JSON.stringify(params.body),
        headers: {...jsonHeaders, ...params.headers}
      })
      .then(response => JSON.parse(response))
      .catch(error => {
        throw Error('Problem fetching JSON from URL ' + params.url + "\n" + error);
      })
    ;

This function is responsible for the JSON encoding and decoding, and will throw errors.  Also notice the keyword parameters. This function too provides defaults, and allows you to override parameters (eg ` headers: {...jsonHeaders, ...params.headers}` will assign the default `jsonHeaders`, and overwrite them with `param.headers` if desired).  This strategy of keyword-parameters-with-default-assignment, is very useful because it reduces the necessary parameters in your callers.

Here is another function that uses `httpFetch`:

    // raw-file fetcher (fileviewer)
    export const getRawFile = (revision, path) => httpFetch({
      url: `${hgHost}/integration/mozilla-inbound/raw-file/${revision}/${path}`
    });
  
Which has now been reduced to one line, and can be in-lined to the caller.

Here is a function that uses `jsonPost`:

    // get coverage from ActiveData for a particular source file
    export const getFileRevisionCoverage = (revision, path) => jsonPost({
      url: `${activeData}/query`,
      body: Query.testCoverage(revision, path)
    });

This is a single line function that is a candidate for in-lining.  Which makes me think about an even simpler function:

    // QUERY ACTIVEDATA
    export const query = (query) => jsonPost({
      url: `${activeData}/query`,
      body: query
    });
    
Which can be used like so (in fileviewer.js):

    /* Fetch coverages from ActiveData */
    FetchAPI.query({
      "from": "coverage",
      "where": {
        "and": [
          {"eq": {"source.file.name": `${this.path}`}},
          {"eq": {"repo.changeset.id12": `${this.revision}`}}
        ]
      },
      "limit": 1000,
      "format": "list"
    })
    .then(data => {
      this.setState({coverage: data});
      // TODO remove these log lines
      console.log(data);
    });

Which is my main point: Using a function that takes a query and returns a resultset.  The query is in-lined to the main code because you are only using it in this one place.  The query also comments itself: you can see it is from `coverage`, and only for a particular `path` and `revision`.

**Comment by yuenj** [comment]
Thanks Kyle, that was some very insightful feedback!  I made a refactor based on what you have up there.  Also, I'll create an issue to integrate a library that can perform exception chaining.
