### ISSUE TITLE
Code line styling problem in fileviewer

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/firefox-code-coverage-frontend#30]
It is not obvious where the styling problem is, but after a load, and moving the mouse pointer over the lines, each line gets ?1px? smaller.  This happens only to lines with code, and only once.

**Comment by LinkaiQi** [comment]
I cannot reproduce the problem. Are we still having the line styling issue?
Made some styling changes to fileviewer in PR #27, does it solve the problem?

**Comment by klahnakoski** [comment]
I will take another look, but not today.  I will post again if I find a problem, or close this.

**Comment by klahnakoski** [comment]
Thisis no longer a problem
