### ISSUE TITLE
Make a facade for logging

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/firefox-code-coverage-frontend#31]
Keeping with all-libraries-should-be-covered-with-a-facade: Please make a facade for the `console.log()` calls.  This facade can simply call `console.log()` or use a real logging library. 

For example, instead of 

    console.log(stat);

call the facade (I am agnostic about the actual names, choose your favorite):

    Log.note(stat);

Here is an example implementation, with optional params.

    Log.note = function(template, params){
      console.log(Mustache.render(template, params);
    }

Be sure you have a plan for how logging can be turned on and off.  For me, I keep it simple:

    if (DEBUG) Log.note(stat);

but there are probably logging libraries that have config options to do this for you.

**Comment by yuenj** [comment]
done!
