### ISSUE TITLE
Colour percentage covered based on the percent value

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/firefox-code-coverage-frontend#32]
Please make the `span.percentage_covered` dynamically assigned according to the percentage; a smooth transition from the `total_uncovered` colour to the `total_covered` color.  

Taking a linear weighted average of the two colours will not work. If this is done a proper colour library is required.  I never found one, and had to make my own [1], but maybe you will be luckier. 

[1] https://github.com/klahnakoski/MoDevMetrics/blob/dev/html/modevlib/charts/aColor.js

**Comment by yuenj** [comment]
I'll be working on this next

**Comment by yuenj** [comment]
done!
