### ISSUE TITLE
Highlight the lines base on total coverage

### ISSUE THREAD

**Issue by LinkaiQi** [klahnakoski/firefox-code-coverage-frontend#33]
Show a number in front of each line represent the number of test that cover it
- 0  ->  it's coverable, but not covered (light-red coloring)
- null -> it's not coverable
- number >= 1  -> it's coverable, 'number' is the number of test cover it (light-green coloring)

**Comment by klahnakoski** [comment]
Be careful with this feature.  Most coverage tools will show a number beside each line indicating ***the number of times it was run***, which is different than what you want to show here.

If you do this, I suggest some other indicator; maybe colouring the background darker for more lines covered; maybe showing a number of dots to the left of the line.

**Comment by LinkaiQi** [comment]
Does ActiveData have the information about **the number of run time (hit time)** of each line?
<img width="912" alt="screen shot 2017-11-07 at 10 51 49 am" src="https://user-images.githubusercontent.com/22087268/32509160-c24af100-c3a9-11e7-8834-facf9c523946.png">

I am implementing this feature, now the number is **the number of test that cover**, I guess the "green circle" needs to be populated with **the number of run time**.

**Comment by klahnakoski** [comment]
There is no hit count in ActiveData at this time.

**Comment by klahnakoski** [comment]
But it looks GREAT!  :)

**Comment by klahnakoski** [comment]
Done!
