### ISSUE TITLE
Make "TestsSideViewer" shows more detail information about the tests

### ISSUE THREAD

**Issue by LinkaiQi** [klahnakoski/firefox-code-coverage-frontend#45]
Make the list of tests in the ```TestsSideViewer```expandable, to show more detail information about each test:
1. Test suite name
2. Test suite chunk
3. Test run platform, maybe?
4. ... Other useful information about the test need to display?

**Comment by LinkaiQi** [comment]
See PR #46

**Comment by klahnakoski** [comment]
I think this is done
