### ISSUE TITLE
Fix routing on the fileviewer

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/firefox-code-coverage-frontend#5]
An example path to the fileviewer is:

http://localhost:3000/#/revision/6b0491f83229/accessible/atk/Platform.cpp

Please change it so that "file" is part of the path. Have the `revision` and `path` be URL parameters (`?`):

http://localhost:3000/file?revision=6b0491f83229&path=/accessible/atk/Platform.cpp

or fragments (`#`) are fine too:

http://localhost:3000/file#revision=6b0491f83229&path=/accessible/atk/Platform.cpp

**Comment by yuenj** [comment]
The paths are not working for me:
http://localhost:3000/#/revision/6b0491f83229/accessible/atk/Platform.cpp
http://localhost:3000/file?revision=6b0491f83229&path=/accessible/atk/Platform.cpp
http://localhost:3000/file#revision=6b0491f83229&path=/accessible/atk/Platform.cpp

What is the path to the file viewer now?

**Comment by LinkaiQi** [comment]
The second URL work for me ( http://localhost:3000/file?revision=6b0491f83229&path=/accessible/atk/Platform.cpp )
Are you pull the least commits from the ucosp branch? What error is showing?

**Comment by yuenj** [comment]
The second URL is working for me now after a fresh pull (I might have mucked around with some of the files).  Thanks.

**Comment by LinkaiQi** [comment]
Also don't forget to use newer revision number to query ActiveData
The revision number (6b0491f83229) in the example doesn't have coverage information
E.x. try (c16bc8097c10, 13a0ffe2798f)

**Comment by klahnakoski** [comment]
This is done
